hl.config({
	decoration = {
		rounding = 10,
		rounding_power = 2.4,
		active_opacity = 1,
		inactive_opacity = 0.7,
		fullscreen_opacity = 1.0,
		dim_inactive = true,
		dim_strength = 0.05,
		dim_special = 0.07,
		blur = {
			enabled = true,
			xray = true,
			special = false,
			new_optimizations = true,
			size = 6,
			passes = 2,
			brightness = 1,
			noise = 0.05,
			contrast = 0.89,
			vibrancy = 0.5,
			vibrancy_darkness = 0.5,
			popups_ignorealpha = 0.6,
			input_methods = true,
			input_methods_ignorealpha = 0.8,
		},
		shadow = {
			enabled = true,
			range = 50,
			offset = "0 4",
			render_power = 10,
			color = "rgba(00000027)",
		},
	},
})
